### ISSUE TITLE
EPIC: Cross-Account Communication

### ISSUE THREAD

**Issue by makisukurisu** [Wandering-Cursor/Samurai-Backend#40]
# Description
Communication is to be recreated as chats with ability to send messages.

Messages, like comments are:
- Text only messages
- OR
- File only messages

Chats should allow communication of multiple Users at the same time, regardless of their type.

# ToDo:

## Chats
- [x] Create;
- [x] Update (Rename, Change Picture?);
- [x] Read;
- [x] Add users (by ID's);

## Messages
- [x] Create;
- [x] Read;

## Web Sockets
General:
- [x] Connection;

### Chats
- [x] New Chat event;
- [x] Chat Updated Event;

### Messages
- [x] New Message Event;
- [x] Typing Event/Action (?);

Sub-Tasks:
- [x] #61
- [x] #62
- [x] #63

**Comment by makisukurisu** [comment]
Models were created, as well as a chat create endpoint.
I have to research how to create WebSocket connection with FastAPI:
https://fastapi.tiangolo.com/advanced/websockets/

**Comment by makisukurisu** [comment]
Deploying this as is to reduce the risk of large merge conflicts to allow focus on the Admin pannel.
