### ISSUE TITLE
Read/Update Tasks for Students and Teachers

### ISSUE THREAD

**Issue by makisukurisu** [Wandering-Cursor/Samurai-Backend#41]
# ToDo

## Users with `tasks` permissions

- [x] GET tasks by project
- [x] GET task by task_id
- [x] UPDATE task's status (/projects/task/{task_id}/status)

## Users with `tasks_editor` permissions

- [x] UPDATE task (description, name, etc.)
- [x] DELETE task
- [x] CREATE task (a new one for some specific Student and Project)

**Comment by makisukurisu** [comment]
```python
from enum import Enum, StrEnum

class Permissions(StrEnum):
...
    TASKS = "tasks"
    TASKS_READ = "tasks:read"
    TASKS_UPDATE = "tasks:update"

    TASKS_EDITOR = "tasks_editor"
    TASKS_EDITOR_UPDATE = "tasks_editor:update"
    TASKS_EDITOR_DELETE = "tasks_editor:delete"
    TASKS_EDITOR_CREATE = "tasks_editor:create"
...
```

Permissions created
