### ISSUE TITLE
Allow to update user projects

### ISSUE THREAD

**Issue by makisukurisu** [Wandering-Cursor/Samurai-Backend#48]
# ToDo

Create a new permission for creating, updating and deleting UserProjects.

`projects_editor` permission series

## Endpoints
- [x] CREATE User Project
- [x] UPDATE User Project
- [x] DELETE User Project

**Comment by makisukurisu** [comment]
Done. Also fixed some issues, and reworked security.
